# Generated by Django 5.2.9 on 2025-12-07 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='user_bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
