"""
PDF report generator for a single assessment result.
"""

import os
# reportlab is the library used to actually build the PDF file — these
# imports bring in the page size, measurement units, colours, the building
# blocks used to lay out the document (paragraphs, tables, spacers), and
# the default text styles to build on top of.
from reportlab.lib.pagesizes import A4
from reportlab.lib.units import mm
from reportlab.lib import colors
from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
)
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle


def generate_report(output_path, ctx):
    """
    ctx: dict with all the values needed for the report. Keeping this as
    a single dict (rather than a long positional-argument list, which is
    what the original app used) avoids argument-order bugs as fields grow.
    """
    # This means: make sure the "reports" folder actually exists before
    # trying to save a file into it — exist_ok=True means it won't error out
    # if the folder is already there.
    os.makedirs(os.path.dirname(output_path), exist_ok=True)

    # Set up the actual PDF document object: page size (A4), and top/bottom
    # margins in millimetres, so text doesn't run right up to the paper edge
    doc = SimpleDocTemplate(output_path, pagesize=A4,
                             topMargin=20 * mm, bottomMargin=20 * mm)
    # Grab reportlab's built-in default styles (fonts, sizes, spacing) to
    # build on top of, rather than defining every text style from scratch
    styles = getSampleStyleSheet()
    # Create a custom title style based on the default "Title" style, but
    # with a specific font size
    title_style = ParagraphStyle("TitleCustom", parent=styles["Title"], fontSize=20)
    h2 = styles["Heading2"]
    normal = styles["Normal"]

    # This means: "story" is the ordered list of everything that will appear
    # on the page, top to bottom — reportlab builds the PDF by working
    # through this list in order, so items get appended to it as we go.
    story = []
    story.append(Paragraph("IoT Device Security Assessment Report", title_style))
    story.append(Spacer(1, 8))

    # Basic device identification info at the top of the report
    story.append(Paragraph(f"<b>Device Name:</b> {ctx['device_name']}", normal))
    story.append(Paragraph(f"<b>Device Type:</b> {ctx['device_type']}", normal))
    story.append(Spacer(1, 12))

    # This means: build a small summary table with the base score, final
    # score, risk level, and compliance status side by side — the first
    # inner list is the header row, the second is the actual data row.
    summary_data = [
        ["Base Score", "Final Score", "Risk Level", "Compliance"],
        [
            f"{ctx['base_score']}/100",
            f"{ctx['score']}/100",
            ctx["risk_level"],
            ctx["compliance_status"],
        ],
    ]
    t = Table(summary_data, colWidths=[100, 100, 100, 120])
    # Style the table: dark header background with white text, thin grey
    # gridlines around every cell, small font size, and everything centered
    t.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#1a1a2e")),
        ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(t)
    story.append(Spacer(1, 16))

    # This means: build a second small table showing exactly how many
    # points were deducted from each of the three penalty sources (CVEs
    # found, actively exploited CVEs, and internet exposure)
    story.append(Paragraph("Penalty Breakdown", h2))
    penalty_data = [
        ["CVE Penalty", "Exploitation Penalty (CISA KEV)", "Exposure Penalty (Shodan)"],
        [f"-{ctx['cve_penalty']}", f"-{ctx['exploitation_penalty']}", f"-{ctx['exposure_penalty']}"],
    ]
    pt = Table(penalty_data, colWidths=[140, 200, 160])
    # Same styling pattern as the summary table, but with a yellow header
    # background instead of dark, to visually distinguish this section
    pt.setStyle(TableStyle([
        ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#f5c518")),
        ("GRID", (0, 0), (-1, -1), 0.5, colors.grey),
        ("FONTSIZE", (0, 0), (-1, -1), 9),
        ("ALIGN", (0, 0), (-1, -1), "CENTER"),
    ]))
    story.append(pt)
    story.append(Spacer(1, 16))

    # This means: list out every recommendation generated by the scoring
    # engine as its own bulleted paragraph line
    story.append(Paragraph("Recommendations", h2))
    for rec in ctx["recommendations"]:
        story.append(Paragraph(f"• {rec}", normal))
    story.append(Spacer(1, 16))

    # This means: list each questionnaire item alongside the real-world
    # security standard/regulation it maps to, and the specific clause
    story.append(Paragraph("Standards Mapping", h2))
    for s in ctx["standards"]:
        story.append(Paragraph(f"• {s['question']} → {s['standard']} ({s['clause']})", normal))
    story.append(Spacer(1, 16))

    # This means: show the raw status of the NVD lookup first (so the
    # reader knows whether this section reflects a real search or a
    # failure), then list every CVE that was found, or say plainly that
    # none were listed if the list came back empty.
    story.append(Paragraph("Detected Vulnerabilities (NVD)", h2))
    story.append(Paragraph(f"<i>Lookup status: {ctx['nvd_status']} — {ctx['nvd_message']}</i>", normal))
    if ctx["vulnerabilities"]:
        for v in ctx["vulnerabilities"]:
            # This means: print each CVE's ID, CVSS score, and severity band
            # in bold, followed by its description — truncated to the first
            # 400 characters so a very long description doesn't blow out
            # the page layout.
            story.append(Paragraph(
                f"<b>{v['cve_id']}</b> — CVSS {v['cvss_score'] or 'N/A'} ({v['severity']})<br/>"
                f"{v['description'][:400]}",
                normal
            ))
            story.append(Spacer(1, 6))
    else:
        story.append(Paragraph("No vulnerabilities listed.", normal))
    story.append(Spacer(1, 12))

    # This means: same pattern as above — show the CISA lookup status first,
    # then either list the actively-exploited CVE IDs found, or say plainly
    # that none were found
    story.append(Paragraph("Actively Exploited Vulnerabilities (CISA KEV)", h2))
    story.append(Paragraph(f"<i>Lookup status: {ctx['cisa_status']} — {ctx['cisa_message']}</i>", normal))
    if ctx["exploited_cves"]:
        story.append(Paragraph(", ".join(ctx["exploited_cves"]), normal))
    else:
        story.append(Paragraph("None found.", normal))
    story.append(Spacer(1, 12))

    # This means: the final section shows the Shodan check's status,
    # the resulting exposure level, and whatever explanatory message came
    # back with it (e.g. "Not Configured", or the number of hosts found)
    story.append(Paragraph("Internet Exposure Intelligence (Shodan)", h2))
    story.append(Paragraph(
        f"<i>Status: {ctx['shodan_status']}</i><br/>"
        f"Exposure Level: {ctx['exposure_level']}<br/>"
        f"{ctx['shodan_message']}",
        normal
    ))

    # This means: actually render the whole "story" list into a real PDF
    # file at output_path, then return that path back to the caller
    doc.build(story)
    return output_path